import type { Metadata } from "next";
import { connection } from "next/server";

import DockflowSwaggerUi from "./SwaggerUi";

export const metadata: Metadata = {
  title: "Dockflow API",
  description: "Интерактивная документация тестового Dockflow API",
};

export default async function DockflowApiPage() {
  // A fresh CSP nonce is generated by proxy.ts for every Swagger page request.
  // Dynamic rendering lets Next.js attach that nonce to its bootstrap scripts.
  await connection();
  return <DockflowSwaggerUi />;
}
