import type { Metadata } from "next";
import { connection } from "next/server";
import { notFound } from "next/navigation";

import DockflowSwaggerUi from "./SwaggerUi";
import { isDockflowDocsEnabled } from "@/lib/security/api-docs";

export const metadata: Metadata = {
  title: "Dockflow API",
  description: "Интерактивная документация тестового Dockflow API",
};

export default async function DockflowApiPage() {
  if (!isDockflowDocsEnabled()) notFound();
  // A fresh CSP nonce is generated by proxy.ts for every Swagger page request.
  // Dynamic rendering lets Next.js attach that nonce to its bootstrap scripts.
  await connection();
  return <DockflowSwaggerUi />;
}
