server {
    listen 80;
    listen [::]:80;
    server_name inventory.yu.edu.kz;
    return 308 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name inventory.yu.edu.kz;

    ssl_certificate /etc/letsencrypt/live/inventory.yu.edu.kz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/inventory.yu.edu.kz/privkey.pem;
    client_max_body_size 8m;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_buffering off;
    }
}
