server {
    listen 80;
    listen [::]:80;
    server_name inventory.yu.edu.kz;

    client_max_body_size 11m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        return 404;
    }
}
